freebsd_instance:
  image_family: freebsd-13-1

task:
  name: compilation (FreeBSD)
  install_script: pkg install -y gmake cmake git
  script:
    - cd src
    - git clone https://github.com/simdjson/simdjson.git
    - cd ..
    - cmake -B build -DCMAKE_INSTALL_PREFIX=.
    - cd build && gmake install

task:
  name: clang-scan (FreeBSD)
  install_script: pkg install -y gmake cmake git devel/llvm llvm
  script:
    - cd src
    - git clone https://github.com/simdjson/simdjson.git
    - cd ..
    - scan-build cmake -B build -DCMAKE_INSTALL_PREFIX=.
    - cd build
    - scan-build --exclude src/simdjson --status-bugs gmake -j
