name: coverity-windows

on: [workflow_dispatch, workflow_call]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-kw-windows
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
    
    - name: coverity-windows
      run: |
        mkdir build
        cd build
        cmake ..
        c:\pcm\ci-cov-windows.ps1

    - name: coverity-windows-cs
      run: |
        mkdir build-cs
        cd build-cs
        cmake ..
        c:\pcm\ci-cov-windows-cs.ps1

    - name: coverity-windows-msr
      run: |
        chdir ${{github.workspace}}\src\WinMSRDriver
        c:\pcm\ci-cov-windows-msr.ps1

    - name: coverity-windows-report
      run: |
        c:\pcm\ci-cov-windows-report.ps1 PCM.windows-all

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: coverity-windows-all-report-${{ github.sha }}
        path: "*-Report.pdf"
