name: tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-test
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        submodules: recursive
    - name: Configure CMake
      run: |
        cmake --version
        rm -rf ${{ github.workspace }}/build
        cmake -B ${{ github.workspace }}/build
    - name: Build
      run: |
        g++ --version
        cd ${{ github.workspace }}/build
        make -j$(nproc)
    - name: Test
      run: |
        set -o pipefail
        sh ${{ github.workspace }}/tests/test.sh 2>&1 | tee test-log.txt

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-log-${{ github.sha }}
        path: test-log.txt

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-log-raw-tr-wo_ext-${{ github.sha }}
        path: build/bin/raw_tr_wo_ext.csv

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-log-raw-tr-wi_ext-${{ github.sha }}
        path: build/bin/raw_tr_wi_ext.csv

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: pcm-csv-${{ github.sha }}
        path: build/bin/pcm.csv

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: pcm-memory-csv-${{ github.sha }}
        path: build/bin/pcm-memory.csv

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-log-raw-tr-wi_ext-single_header-${{ github.sha }}
        path: build/bin/raw_tr_wi_ext_single_header.csv

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-log-raw-edp-${{ github.sha }}
        path: build/bin/raw_edp.txt

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-log-raw-json-${{ github.sha }}
        path: build/bin/raw_json.json

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: test-log-raw-edp-offlined-cores-${{ github.sha }}
        path: build/bin/raw_edp_offlined_cores.txt
